language: csharp
solution: Unosquare.Labs.LiteLib.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
mono:
  - latest
  - 4.2.1
os:
  - linux
  - osx
install:
  - nuget restore Unosquare.Labs.LiteLib.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get install sqlite; fi
script:
  - xbuild /p:Configuration=Mono Unosquare.Labs.LiteLib.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe --process=Single ./test/Unosquare.Labs.LiteLib.Tests/bin/Mono/Unosquare.Labs.LiteLib.Tests.dll
